const COUNTRY_NAMES = {
  MEX: 'Mexico',
  USA: 'United States',
  CAN: 'Canada',
  COL: 'Colombia',
  GTM: 'Guatemala',
  HND: 'Honduras',
  SLV: 'El Salvador',
  NIC: 'Nicaragua',
  CRI: 'Costa Rica',
  PAN: 'Panama',
  BRA: 'Brazil',
  PER: 'Peru',
  ECU: 'Ecuador',
  VEN: 'Venezuela',
  CHL: 'Chile',
  ARG: 'Argentina',
  DOM: 'Dominican Republic',
  CUB: 'Cuba',
  HTI: 'Haiti',
  JAM: 'Jamaica',
  CHN: 'China',
  IND: 'India',
  PHL: 'Philippines',
  VNM: 'Vietnam',
  KOR: 'South Korea',
  JPN: 'Japan',
  GBR: 'United Kingdom',
  DEU: 'Germany',
  FRA: 'France',
  ITA: 'Italy',
  ESP: 'Spain',
  RUS: 'Russia',
  NGA: 'Nigeria',
  EGY: 'Egypt',
  PAK: 'Pakistan',
  BGD: 'Bangladesh',
  TUR: 'Turkey',
  IRN: 'Iran',
  IRQ: 'Iraq',
  SAU: 'Saudi Arabia',
};

export default COUNTRY_NAMES;